producers/miniTLU/include/tlu/miniTLUController.hh
producers/miniTLU/src/miniTLUController.cc
producers/miniTLU/src/miniTLU_Producer.cxx

miniTLU producer is now able to deal with single word 64-bit packets and it handles correctly the case when FIFO reads splits a 2-word packet.
Tested with a miniTLU without errors.

miniTLU aidaPacket threaded

---

main/exe/src/TestRunControl.cxx

added functionality:
new command line option to make the run control scriptable

new functionality: run control can now be scripted

---

main/lib/plugins/USBPixI4ConverterPlugin.cc

I've lost track of the various branches - please ensure these changes also propagate into any other branch!

Fixing wrong vector access in USBPixI4ConverterPlugin

---

.gitignore
debug/.gitignore
main/include/eudaq/DataConverterPlugin.hh
main/lib/plugins/DataConverterPlugin.cc
main/lib/plugins/SCTUpgradeConverterPlugin.cc
main/lib/src/FileWriterLCIO.cc
nreader/include/EUTelAPIXMCDetector.h
nreader/include/EUTelBaseDetector.h
nreader/include/EUTelCMSPixelDetector.h
nreader/include/EUTelDEPFETDetector.h
nreader/include/EUTelFortisDetector.h
nreader/include/EUTelMimoTelDetector.h
nreader/include/EUTelMimosa18Detector.h
nreader/include/EUTelMimosa26Detector.h
nreader/include/EUTelPixelDetector.h
nreader/include/EUTelSetupDescription.h
nreader/include/EUTelTLUDetector.h
nreader/include/EUTelTakiDetector.h
nreader/include/EUTelTimepixDetector.h

LCIO Converter for the SCT data converter.
new generic function for convertion between EUDAQ planes and LCIO data container.
Changes to the lcio file writer to make it more compatable with the nreader 
added DLL Export for Detector description DLL

Sct converter based on v1.4dev

---

main/include/eudaq/Utils.hh
main/lib/plugins/EUDRBConverterPlugin.cc
main/lib/plugins/NIConverterPlugin.cc
main/lib/plugins/SCTUpgradeConverterPlugin.cc
main/lib/src/Utils.cc
monitors/offlinemon/src/CorrelationPlots.cpp
monitors/offlinemon/src/CorrelationPlots_interface.cpp
monitors/offlinemon/src/CorrelationVSTimePlots.cpp
monitors/offlinemon/src/OfflineMonitor.cxx
monitors/offlinemon/src/Planes.cpp
monitors/offlinemon/src/makeCorrelations.cpp
producers/root/src/ROOTProducer.cpp

new fuinction to convert bool arrays to char vectors and revers.
bug fix:
missing include 
bind2nd needs 
#include <xfunctional>
to be included
optic:
m_corr.at(i)->Draw("colz");
makes nicer plots for the offline mon

Bool2char converter

---

main/include/eudaq/LogSender.hh
main/lib/src/LogSender.cc
producers/root/inc/ROOTProducer.h
producers/root/src/ROOTProducer.cpp

bugfixes:
[CORE]
allow multiple producer from one program
[ROOTProducer]
removed race condition between set status function and send event function by adding a delay.

Root producer

---

main/include/eudaq/Event.hh
main/lib/src/Event.cc
producers/root/inc/ROOTProducer.h
producers/root/src/ROOTProducer.cpp

this makes it possible to read in eudaq 2 files with EUDAQ1.x.

Support for eudaq2 files in euda 1.x

---

main/lib/src/PALPIDEFSConverterPlugin.cc

Hi,
We found and corrected a bug in our converter for the pALPIDEfs chip and we would like to merge the change to the official repository.
Best regards,
Monika

Bug in the pALPIDEfs converter

---

main/lib/src/PALPIDEFSConverterPlugin.cc
producers/palpidefs/src/PALPIDEFSProducer.cxx

Local changes in pALPIDEfs producer and converter 
Thanks in advance for merging

Bug fixes for converter, loser timestamp cut

---

main/lib/src/PALPIDEFSConverterPlugin.cc
producers/palpidefs/scripts/watchdog.py

Hi,
thanks a lot in advance for merging!
Felix

Improved handling of corrupt data in the converter

---

main/include/eudaq/CMSPixelHelper.hh

CMSPixproducer

---

etc/scripts/STARTRUN.palpidefs
producers/palpidefs/include/PALPIDEFSProducer.hh
producers/palpidefs/src/PALPIDEFSProducer.cxx
producers/palpidess/include/DevicePalpidess.hh
producers/palpidess/src/DevicePalpidess.cc
producers/palpidess/src/PalpidessProducer.cxx

Local changes to the pALPIDEfs:
- linear stage handling
- code beautification
and the pALPIDEss
- code beautification

Updates to the pALPIDEfs and pALPIDEss producers

---

etc/scripts/STARTRUN.palpidefs
producers/palpidefs/scripts/hameg2030.py
producers/palpidefs/scripts/watchdog.py
producers/palpidefs/scripts/watchdog_config.py
producers/palpidefs/src/PALPIDEFSProducer.cxx

Hello,
just another update of our producer.
Thanks for merging!

Update of the pALPIDEfs producer

---

producers/palpidefs/include/PALPIDEFSProducer.hh
producers/palpidefs/scripts/logviewer.sh
producers/palpidefs/scripts/power_off.py
producers/palpidefs/scripts/power_on.py
producers/palpidefs/scripts/power_status.py
producers/palpidefs/src/PALPIDEFSProducer.cxx
producers/palpidess/src/PalpidessProducer.cxx

- improved the stability of the End-Of-Run/Start-Of-Run behaviour of the pALPIDEfs producer
Thanks a lot for merging!

Stability improvements in the pALPIDEfs producer

---

main/exe/src/Converter.cxx

I overlooked some debug code that is removed with this commit 
& 
Clean up

clean up of the  Converter

---

main/lib/plugins/DefaultConverterPlugin.cc
main/lib/plugins/SCTConverterPlugin.cc
main/lib/plugins/SCTUpgradeConverterPlugin.cc
main/lib/src/FileWriterLCIOC.cc

Fix some compilation issues on v2.0 when compiling with LCIO/EUTELESCOPE and LCIO alone (issue #173).

Develop on master

---

main/lib/plugins/CcpdlfADCConverterPlugin.cc
main/lib/plugins/CcpdlfConverterPlugin.cc
main/lib/plugins/GenericConverterPlugin.cc

Converter plugins for generic and ccplf

Converter plugins for generic producer and ccplf producers

---

appveyor.yml

repaired branch names in appveyor.yml

Wrong branch name in appveyor.yml

---

gui/include/euRun.hh
gui/src/euRun.cc

which broke when config loading was changed (this functionality was not tested afterwards). Now it also stops after the last config file, which probably did not work properly before.

Fixed automatic configuration file changing in euRun

---

.travis.yml
main/lib/plugins/APIX-CT-ConverterPlugin.cc
main/lib/plugins/CcpdlfADCConverterPlugin.cc
monitors/onlinemon/include/GraphWindow.hh
monitors/onlinemon/src/CorrelationHistos.cc
monitors/onlinemon/src/GraphWindow.cc
monitors/onlinemon/src/OnlineMon.cxx
monitors/onlinemon/src/TGraphSet.cc

As in master, minus the jsoncons and latex cmake update - compatibility?

Fixed MSVC warnings (1.5-dev)

---

main/lib/plugins/CaliceGenericConverterPlugin.cc

following @arummler  advice #197

Solve warning with MSVC in CaliceGenericConverterPlugin 

---

main/include/eudaq/RawDataEvent.hh
producers/root/CMakeLists.txt
producers/root/inc/DemoHardware.h
producers/root/inc/ROOTProducer.h
producers/root/src/DemoHardware.cpp
producers/root/src/ROOTProducer.cpp

@arummler  
Here is the sync PR #207 .  The base code of RawdataEvent from v1.5 and master are not same.

General Inferface of ROOTProducer with RawdataEvent  (sync #207 master push)

---

main/lib/plugins/CaliceGenericConverterPlugin.cc

 Solve warning with MSVC in CaliceGenericConverterPlugin. Master branch.

---

.travis.yml
gui/include/euLog.hh
gui/include/euRun.hh
gui/src/euLog.cc
gui/src/euRun.cc
gui/ui/euRun.ui
main/exe/src/TestRunControl.cxx
main/lib/plugins/CcpdlfADCConverterPlugin.cc
main/lib/src/FileWriterTextCompact.cc
monitors/onlinemon/include/GraphWindow.hh
monitors/onlinemon/src/CorrelationHistos.cc
monitors/onlinemon/src/GraphWindow.cc
monitors/onlinemon/src/OnlineMon.cxx
monitors/onlinemon/src/TGraphSet.cc

There are still about 28 left. More commits to come.

Fixed MSVC warnings

---

cmake/UseLATEX.cmake
doc/manual/CMakeLists.txt

https://github.com/kmorel/UseLATEX/releases

Master: Updated UseLATEX.cmake macro to version 2.2.1 from

---

appveyor.yml

http://help.appveyor.com/discussions/problems/4637-code-1

Changing appveyor.yml to solve code 1 problem according to

---

appveyor.yml
monitors/onlinemon/include/SimpleStandardEvent.hh

#233 
try to fix. No windows on hand.

onlinemonitor: (try) fix build failure on Windows

---

producers/palpidefs/include/PALPIDEFSProducer.hh
producers/palpidefs/scripts/zaber.py
producers/palpidefs/src/PALPIDEFSProducer.cxx

localized changes in palpidefs producer to include zaber rotary stages

pALPIDEfs: rotary stage integration

---

main/lib/plugins/APIX-CT-ConverterPlugin.cc
main/lib/plugins/CcpdlfADCConverterPlugin.cc
main/lib/plugins/CcpdlfConverterPlugin.cc
main/lib/plugins/DataConverterPlugin.cc
main/lib/plugins/EUDRBConverterPlugin.cc
main/lib/plugins/Mupix2ConverterPlugin.cc
main/lib/plugins/Mupix3ConverterPlugin.cc
main/lib/plugins/Mupix4ConverterPlugin.cc
main/lib/plugins/NIConverterPlugin.cc
main/lib/plugins/PyBARConverterPlugin.cc
main/lib/plugins/USBPixI4ConverterPlugin.cc
main/lib/plugins/USBpixConverterPlugin.cc

EUDAQ interfacing LCIO via EUTel

---

main/lib/plugins/APIX-CT-ConverterPlugin.cc
main/lib/plugins/CcpdlfADCConverterPlugin.cc
main/lib/plugins/CcpdlfConverterPlugin.cc
main/lib/plugins/DataConverterPlugin.cc
main/lib/plugins/EUDRBConverterPlugin.cc
main/lib/plugins/Mupix2ConverterPlugin.cc
main/lib/plugins/Mupix3ConverterPlugin.cc
main/lib/plugins/Mupix4ConverterPlugin.cc
main/lib/plugins/NIConverterPlugin.cc
main/lib/plugins/PyBARConverterPlugin.cc
main/lib/plugins/USBPixI4ConverterPlugin.cc
main/lib/plugins/USBpixConverterPlugin.cc

Modern - TEST PLEASE: EUDAQ interfacing LCIO via EUTel 

---

producers/palpidefs/conf/palpidefs/full_pALPIDE-3.xml
producers/palpidefs/conf/palpidefs/full_pALPIDE-3template.xml
producers/palpidefs/include/PALPIDEFSProducer.hh
producers/palpidefs/src/PALPIDEFSConverterPlugin.cc
producers/palpidefs/src/PALPIDEFSProducer.cxx

Master integrate v17 - Palipidefs

---

CMakeLists.txt
appveyor.yml
appveyor/install_afs.ps1

Appveyor CI: Improvement

---

CMakeLists.txt
etc/tools/runsplitter/CMakeLists.txt
etc/tools/runsplitter/src/Runsplitter.cc

Runsplitter divides large .raw files into several smaller files for parallel processing.
CMake flag: -DBUILD_runsplitter
Default: ON

Added EURunsplitter to the tools section

---

main/lib/plugins/APIX-CT-ConverterPlugin.cc
main/lib/plugins/USBPixI4ConverterPlugin.cc
main/lib/src/FileWriter.cc
main/lib/src/FileWriterRoot.cc

e.g. FE-I4 DUTs were not converted in the data stream

V1.7 dev extending converter

---

.travis.yml
cmake/Platform.cmake
user/eudet/module/src/NIConverterPlugin.cc

Error in NIproducer: template and C++14 required (probably).

Master fix ni

---

.travis/install_palpidefs_driver.sh
main/lib/plugins/PALPIDEFSConverterPlugin.cc

- Attempt to get rid of the VERSION variable

Update to the CI scripts

---

.travis.yml

V1.7 dev update versions ci

---

.travis/install_palpidefs_driver.sh
appveyor/install_palpidefs_driver.ps1

updated the path to the archive with the ALPIDE software needed for the palpidefs producer

updating the software path

---

.travis/install_tex.sh

CI: More quick fixes for master branch

---

.travis.yml
.travis/set_compilers.sh
.travis/update_repositories.sh
cmake/Platform.cmake
doc/manual/src/Integration.tex

http://mailman.isi.edu/pipermail/ns-developers/2016-February/013378.html
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=69470

Workaround for xfer_bufptrs public/private bug in sstream header

---

gui/src/euRun.cc

gui: show a messagebox when ini/conf file does not exist

---

main/include/eudaq/Utils.hh
main/lib/src/Utils.cc
producers/drs4/src/DRS4Producer.cxx

V1.7 dev fix drs4

---

user/eudet/hardware/src/FmctluController.cc
user/eudet/module/src/FmctluProducer.cc

Found a couple of bugs in the Producer and Hardware files for the TLU.

Fixed bug in DAC configurations in TLU Producer 

---

user/eudet/hardware/src/NiController.cc

as described in manual using EUDAQ_THROW

Modernizing error handling in NI producer

---

user/tlu/CMakeLists.txt
user/tlu/exe/CMakeLists.txt
user/tlu/exe/src/EudetTluControl.cxx
user/tlu/exe/src/EudetTluReset.cxx

for example: EudetTluControl formerly TLUControl

adjust cmake-files for stand-alone programs of EUDET TLU

---

.travis.yml
appveyor.yml
main/lib/plugins/BDAQ53ConverterPlugin.cc
main/lib/src/AidaFileWriter.cc

CI: version upgrades and fixes

---

main/lib/python/CMakeLists.txt
user/example/python/ExamplePyDataCollector.py
user/example/python/ExamplePyProducer.py
user/example/python/setup_eudaq.sh
user/example/python/startRun_ExPy.sh

-- user/example/python modified for tutorial usage
-- 1 known issue: python example DataCollector to be fixed

Tutorial python section update

---

user/example/misc/Ex0.conf
user/example/python/ExamplePyDataCollector.py
user/example/python/startRun_ExPy.sh

link to PR https://github.com/eudaq/eudaq/pull/515/commits/feaf2769c8a45e634c0b9e1f1a62e0bee81afe29 
Tutorial py update 
cherry-pick the commit

fix bug in ExpyDataCollector

---

main/lib/core/src/LogMessage.cc

just a minor style change just because Yi and myself had a chat about it

added some colors to logger cout and put the data/time first

---

main/lib/core/src/RunControl.cc
user/aidastrip/exe/src/lycorisCliConverter.cxx
user/aidastrip/misc/01_aida_tlu_noDC_mod
user/aidastrip/misc/aidastrip_test.conf
user/aidastrip/misc/aidastrip_test.ini
user/aidastrip/misc/example_startrun.sh
user/aidastrip/misc/only-tlu_mod.conf
user/aidastrip/misc/runKpix.sh
user/aidastrip/module/src/kpixProducer.cc
user/aidastrip/module/src/kpixRunControl.cc

-- user/aidastrip modules up-to-date
-- NEW: adding the EUDAQ_CTRL_PRODUCER_FIRST_STOP for user to choose a producer to stop first.

Mewu.dev.new

---

gui/include/euRun.hh
gui/src/euRun.cc

Replaced auto definitions in prototypes by actual type.

Solving issue #533

---

gui/include/euRun.hh
gui/src/euRun.cc
gui/src/euRun.cxx
gui/ui/euRun.ui
main/lib/core/include/eudaq/Logger.hh
main/lib/core/include/eudaq/RunControl.hh
main/lib/core/src/Configuration.cc
main/lib/core/src/RunControl.cc

Yesterday I found several commits from myself in the master branch that should not be there yet. 
I reverted these changes.
Unfortunately I do not know how these features ended up in the master.
As reverting parts is something I didn't need to do anytime before please check this request carefully before merging it.  It compiles and the example scripts are running on linux.

Revert scan features

---

main/python/src/PyTluProducer.cpp
python/PyEUDAQWrapper.py

This pull request fixes the pytlu producer. It is now a working and tested version of the [pytlu producer](https://github.com/SiLab-Bonn/pytlu/pull/22) avalaible for eudaq 1.x-dev.

Small fixes PyTLU producer

---

gui/README.md
gui/include/scanHelper.hh
gui/src/euRun.cc
user/MuPix8/module/src/MuPix8RawEvent2StdEventConverter.cc
user/example/misc/scan/example_startrun.sh

scan Improvements, clean version

Merge scan

---

README.md

Fixes the travis badge for master branch.

CI: Fix README badge after swap of travis org --> com

---

user/tlu/exe/src/euCliTluReader.cxx

... from subevent tag correctly.
Discovered when looking at data taken at DESY with the AIDA TLU.

euCliTluReader: fix bug to read fine timestamp and scalers

---

.travis/install_wiringpi.sh
appveyor.yml
cmake/FindwiringPi.cmake

Replaced by inofficial one as wiringPI depreciated by maintainer. Might need to switch library in the future.

FIX: wiringPI repo

---

user/timepix3/module/include/Timepix3Event2StdEventConverter.hh
user/timepix3/module/src/Timepix3Event2StdEventConverter.cc

Sorry @herkerta that was me committing.... :)

TImepix3: make delta_t0 work as expected

---

user/eudet/module/src/NiRawEvent2StdEventConverter.cc

EUDET: Don't fail on nullptr config object

---

cmake/UseLATEX.cmake
doc/manual/CMakeLists.txt
doc/manual/src/Producers.tex
doc/manual/src/TTreeConverter.tex
doc/manual/src/preamble.tex

Fixing a couple latex issues in manual.

Master update latex

---

user/timepix3/module/src/Timepix3Producer.cxx

* Silence known bogus `0x6000` error on initialize
* Improve run loop
* Reduce timeout for SPIDR buffer read to 300ms in the hope that it would create smaller chunks

Timepix3: some improvements

---

monitors/onlinemon/src/EUDAQMonitorCollection.cc
monitors/onlinemon/src/MonitorPerformanceCollection.cc
monitors/onlinemon/src/ParaMonitorCollection.cc

Fix for issue #649 
to be tested on root 6.22 @herkerta

updating to new root version

---

monitors/onlinemon/src/HitmapCollection.cc

missed the fix in one file - sorry

fixed last issue for 649

---

main/lib/core/include/eudaq/Configuration.hh
main/lib/core/src/Configuration.cc

Add Get() method of type float to Configuration class.

Configuration: add float Get()

---

main/lib/core/include/eudaq/StandardPlane.hh
main/lib/core/src/StandardPlane.cc

as title says.
I will improve the interface still a bit , but basic functionality is there.

StandardPlane: add possibility for waveforms

---

CMakeLists.txt

This MR will be tagged as version 2.5.0 and will be used for a release.
Main new feature: StandardEvent is now supporting Waveforms

Release  2.5.0

---

main/lib/python/src/PybindEUDAQ.cc
main/lib/python/src/PybindLogger.cc

This first time I'm using `pybind11` so I'm open to all suggestions how to make this more elegant.

Python bindings for EUDAQ logger

---

main/lib/core/include/eudaq/LogMessage.hh
main/lib/core/src/StandardPlane.cc
user/tlu/module/src/TluRawEvent2StdEventConverter.cc

Fixing a warning and an error when compiling on macOS - needs cross check on unix

Tlu converter cast

---

CMakeLists.txt

You first tagged v2.5.0 and then found the issue with ResizeSZ, so we need to re-release

Bump Version to v2.5.2

---

main/lib/core/include/eudaq/StandardPlane.hh
main/lib/core/src/StandardPlane.cc

This implements the weird CDS and ACCUMULATE stuff for waveforms, a bit hackily because we don't subtract the frames for CDS actually.

Waveforms: SetupResults

---

user/tlu/module/src/TluRawEvent2StdEventConverter.cc

Fix fine timestamp bug in TluRawEvent2StdEventConverter.cc

Corrected difference tags DIFF_FINETS23_del_ns onwards

---

user/cmspixel/module/include/CMSPixelProducer.hh
user/cmspixel/module/src/CMSPixelProducer.cxx

Fixing issue on CMSPixel configuration that keeps adding ROCs to the DUT.

CMSPixel: Fix configuration issue

---

user/caribou/module/include/CaribouEvent2StdEventConverter.hh
user/caribou/module/src/H2MEventConverter.cc

Draft of the H2M Converter - to be tested this week

H2M Converter

---

CMakeLists.txt

CMake: Do not export system-wide package to package registry

---

user/CMakeLists.txt
user/alibava/CMakeLists.txt
user/alibava/README.md
user/alibava/misc/alibava_startrun.sh
user/alibava/module/CMakeLists.txt
user/alibava/module/src/AlibavaProducer.cc

and optionally extern HV setting programm
We currently run this with an alibava testbeam at DESY

add simple alibava producer which calls external alibava-gui

---

user/itkstrip/exe/src/ItsOccupancyScanner.cxx
user/itkstrip/itsroot/CMakeLists.txt
user/itkstrip/itsroot/src/ROOTProducer.cc
user/itkstrip/module/src/ItsAbcCommon.h
user/itkstrip/module/src/ItsAbcRawEvent2StdEventConverter.cc

These are changes by @heyajun093 made for the atlas itk strips community. If someone mind to review

Changes for i tk

---

user/ITS3/README.md
user/ITS3/misc/.gitignore
user/ITS3/misc/ITS3start.py
user/ITS3/misc/conf_examples/ITS3-MOSS-test.conf
user/ITS3/misc/conf_examples/ITS3-MOSS-test.ini
user/ITS3/misc/conf_examples/ITS3-OPAMP-test.conf
user/ITS3/misc/conf_examples/ITS3-OPAMP-test.ini
user/ITS3/misc/conf_examples/ITS3-align.conf
user/ITS3/misc/conf_examples/ITS3.ini
user/ITS3/module/CMakeLists.txt
user/ITS3/module/src/MOSSRawEvent2StdEventConverter.cc
user/ITS3/module/src/OPAMPRawEvent2StdEventConverter.cc
user/ITS3/python/ALPIDEProducer.py
user/ITS3/python/APTSProducer.py
user/ITS3/python/DPTSProducer.py
user/ITS3/python/ITS3DataCollector.py
user/ITS3/python/ITS3RunControl.py
user/ITS3/python/MOSSProducer.py
user/ITS3/python/OPAMPProducer.py
user/ITS3/python/PowerProducer.py
user/ITS3/python/TriggerProducer.py
user/ITS3/python/spillcounter.py
user/ITS3/python/utils.py
user/ITS3/requirements.txt
user/ITS3/scripts/DPTSDump.py
user/ITS3/scripts/OPAMPDump.py
user/ITS3/scripts/RunListAssembler.py
user/ITS3/scripts/watchdog.py
user/ITS3/scripts/zaber_serial_controller.py

- New producers and converters (MOSS & OPAMP)
- Updated python Run Control and Data Collector
- Various updates of helper scripts

Update ITS3 user code

---

user/caribou/README.md
user/caribou/module/include/CaribouEvent2StdEventConverter.hh
user/caribou/module/src/dSiPMEventConverter.cc

@gianpierovignola please review :)

dSiPM: implement changes from TB4

---

user/caribou/module/src/H2MEventConverter.cc

H2M: add option to define time stamp w.r.t. the frame end.

H2M: add option to define time stamp w.r.t. the frame end.

---

user/caribou/CMakeLists.txt
user/caribou/module/src/CaribouProducer.cxx

This PR relates to the Peary PR https://gitlab.cern.ch/Caribou/peary/-/merge_requests/205 where modification were made to the configuration class. It adapts for the modification in the CaribouProducer

Fixing use of Caribou Peary configuration class in CaribouProducer

---

user/caribou/module/include/CaribouEvent2StdEventConverter.hh

Don't want to include root in Converter header

forward declaration of TFile

---

user/piStage/hardware/CMakeLists.txt

`PI_FOUND` contains the library path. Use it :)

Fix building PI stage controller

---

user/caribou/module/include/CaribouEvent2StdEventConverter.hh
user/caribou/module/src/DSO9254AEventConverter.cc

* Formatting
* Fixing trigger ID overflow correction
* Making channel mapping configurable

Post TB updates of the DSO9254AEvent2StdEventConverter

---

user/caribou/README.md
user/caribou/module/include/CaribouEvent2StdEventConverter.hh
user/caribou/module/src/H2MEventConverter.cc

H2M: add frame ID back-jump detection logic

---

main/exe/src/euCliReader.cxx

euCliReader has an option flag `"s", "statistics"`  that promises to `"enable print of statistics"`  but currently does nothing (it's not even checked). 
This commit makes it output at least the trigger number range and a list of devices found in the data.
Example output:

Fill euCliReader stat flag with a little bit of life

---

user/timepix4/module/src/Timepix4Producer.cxx

@kraemeru 
Set the run number as folder name - we can extend this to whatever we need if we want

naming the folder after the run number

---

user/caribou/CMakeLists.txt
user/caribou/module/src/CLICTDEventConverter.cc
user/caribou/module/src/CLICpix2EventConverter.cc
user/caribou/module/src/H2MEventConverter.cc
user/caribou/module/src/dSiPMEventConverter.cc

Caribou: fix include paths for latets version

---

user/tlu/module/src/TluRawEvent2StdEventConverter.cc

directly and without pre-decoding in the producer
@stephanlachnit needs to be tested with data.

User/TLU: add support for the TLU raw data format
