eudaq/eudaq

producers/tlu/src/TLUProducer.cxx
It's always a good idea to set a required flag before invoking a function that needs it... In this case, the flag indicating whether or not a TLU that has been modified to generate 0->2V Vcntl signals to the PMTs was being set after the Vcntl voltages, so it would fail if using a so-modified TLU. This bug had no impact unless the modified TLU feature was being used.
=> Swapped SetPMTVcntlMod and SetPMTVcntl

.travis.yml
this should allow us to run Travis CI automated builds again on v1.4-dev branch. Added some features (e.g. building of the python modules).
Deactivated Clang build for now because it has problems with finding STL headers onn the Ubuntu 12 machine the build is running on. To be investigated and solved.
=> Update Travis CI build script

main/lib/src/DataCollector.cc, main/lib/src/FileSerializer.cc, monitors/onlinemon/include/OnlineMon.hh, monitors/onlinemon/src/OnlineMon.cxx, producers/cmspixel/include/CMSPixelProducer.hh, producers/cmspixel/src/CMSPixelConfigParser.cxx, producers/cmspixel/src/CMSPixelProducer.cxx
Fixes some bugs in Online monitor enabling direct running from RunControl again.
Fixes some bugs in DataCollector enabling Online Monitoring of data taken without TLU.
Changes the behaviour of CMSPixelProducer when reading DACs.
=> OnlineMon & DataCollector fixes + CMSPixelProducer update

CMakeLists.txt, monitors/onlinemon/include/HitmapHistos.hh, monitors/onlinemon/src/EUDAQMonitorCollection.cc, monitors/onlinemon/src/HitmapCollection.cc, monitors/onlinemon/src/HitmapHistos.cc, monitors/onlinemon/src/OnlineMon.cxx
* Fix crash if nPlanes change between two runs (e.g. added new producer and reconfigured)
* Fix crash when "AutoReset" was activated before first run was started
* Add new projected hitmap histograms
=> Fixes to OnlineMonitor

CMakeLists.txt, cmake/uninstall.cmake.in, gui/include/euLog.hh, gui/src/euLog.cc, main/exe/src/TestLogCollector.cxx, main/include/eudaq/LogCollector.hh, main/lib/src/LogCollector.cc
With this commit it is possible to specify the log file output directory at startup of the LogCollector (both TestLogCollector and euLog). Defaults to old behavior ("../logs"). 
This is a first step towards removing all content directories from the EUDAQ source tree
=> LogCollector: allow specification of the logging directory

main/lib/plugins/CaliceGenericConverterPlugin.cc, main/lib/plugins/CcpdlfConverterPlugin.cc
- /home/travis/build/eudaq/eudaq/main/lib/plugins/CcpdlfConverterPlugin.cc:61:25:
& has lower precedence than !=; != will be evaluated first [-Wparentheses]
if (data[3] & 0x80 !=0x80) return (unsigned) -1;
according to issue #182
Needs to be checked by maintainer of this system but the other possibility does not make sense.
-
=> Fix compiler & Co warnings

.travis.yml
and mac is not really the environment which runs on RPis.
=> Disable rpi controller on mac as wiringPi does not build out of the box

main/lib/plugins/NIConverterPlugin.cc
The missing flag FLAG_ACCUMULATE results in discarding the second M26 frame.
It is still read from the raw data and decoded, but the LCIO routine only
reads the first frame stored.
This affects all analyses using the NIConverterPlugin to convert M26 raw data to
StandardEvent or LCIO.
It has been discovered in CMS pixel data which showed correlation with the M26
planes in the OnlineMonitor, but not in LCIO. This data was apparently recorded
with a timing difference correlating the CMS hits with the second M26 frame.
The OnlineMon uses the StandardPlane format, reading all frames and thus shows
the correlation. The EUTelescope analysis uses the converted LCIO format
where the second frame and thus the correlation was lost.
This effect had first been seen already in 2015 CMS data taken at …
=> Fix major bug in NI converter: losing 2nd M26 frame when converting to LCIO

user/eudet/module/src/NIConverterPlugin.cc
The missing flag FLAG_ACCUMULATE results in discarding the second M26 frame.
It is still read from the raw data and decoded, but the LCIO routine only
reads the first frame stored.
This affects all analyses using the NIConverterPlugin to convert M26 raw data to
StandardEvent or LCIO.
It has been discovered in CMS pixel data which showed correlation with the M26
planes in the OnlineMonitor, but not in LCIO. This data was apparently recorded
with a timing difference correlating the CMS hits with the second M26 frame.
The OnlineMon uses the StandardPlane format, reading all frames and thus shows
the correlation. The EUTelescope analysis uses the converted LCIO format
where the second frame and thus the correlation was lost.
This effect had first been seen already in 2015 CMS data taken at …
=> EUDAQ2: Fix major bug in NI converter: losing 2nd M26 frame when converting to LCIO

main/include/eudaq/CMSPixelHelper.hh
Correctet main/include/eudaq/CMSPixelHelper.hh which prevents me from compiling NREADER with CMSPIXEL
=> Fix to account for the new templated methods in eutelescope

.gitignore, user/eudet/hardware/include/FmctluController.hh, user/eudet/hardware/src/FmctluController.cc, user/eudet/misc/fmctlu_runcontrol.conf, user/eudet/module/src/FmctluProducer.cc
- _gitignore_: added test.conf and test.ini. From now on use those files for local tests, only push to _fmctlu_runcontrol.conf_ and _fmctlu_runcontrol.ini_ if there is a meaningful change.
- _FmctluController.cc_ : fixed minor bug in expander configuration, for consistency.
- _FmctluProducer.cc_ : fixed issue with writing of the firing trigger outputs. Up to now the producer was writing an empty string. It should now correctly display a 6-bit boolean string where each bit correspond to an input firing (1) or not (0). Input0 is the LSB.
=> Currentdev: fixed bug in I2C expander code. Fixed issue with producer not showing firing inputs.

main/lib/core/src/Event.cc
…y harmful through hiding on other platforms):
error C2761: 'void eudaq::Event::AddSubEvent(eudaq::EventSPC)': redeclaration of member is not allowed
error C2761: 'void eudaq::Event::SetTimestamp(uint64_t,uint64_t,bool)': redeclaration of member is not allowed
=> Fixing compilation error on Windows

gui/include/RunControlModel.hh, gui/include/euRun.hh, gui/src/RunControlModel.cc, gui/src/euRun.cc, main/lib/core/include/eudaq/RunControl.hh, main/lib/core/src/RunControl.cc, user/eudet/hardware/include/NiController.hh, user/eudet/hardware/src/NiController.cc, user/eudet/module/src/NiProducer.cc
This addresses issue #409 : Right click on any connection offers the possibility to send "Reset" or "Terminate" to this particular command receiver only. Testing with ni producer (without attached hardware) shows unexpected implementation within ni producer: Instead of propagating error to run control it only sends message, waits 60 seconds and terminates. It should use SetState explicitly. Up to that step when it ends in error (and also individual reset does not work...needs follow-up) the individual terminate works fine. Could be also easily extended to individual init and config (and start/stop for slowproducers).  What needs checking is whether it does not break the FSM logic --> consequences for global state.
=> Send command to individual producer

main/lib/plugins/APIX-CT-ConverterPlugin.cc
The hits of APIX quad modules were displayed wrongly in the OnlineMonitor: Rows are on x-Axis, cols are on y-Axis.
This is fixed by swapping col and row arguments in SetSizeZS() function. With this, the an if statement becomes unnecessary, so it was removed.
This targets eudaq/eudaq/issues/401.
=> Fixes wrong display of APIX quad module in OnlineMonitor

main/python/src/PyProducer.cpp, python/PyEUDAQWrapper.py
Thus far it was not possible to access the Config Parameters using the Python interface. This is fixed with this PR.
=> [Python interface] Fix get config parameter function and add error checks

main/python/src/PyProducer.cpp, python/PyEUDAQWrapper.py
The run number is set after Run Start is issued from run control and can be used e.g. to set an appropriate file name in the python producer, depending on run number.
=> [Python interface] Add ability to get the actual run number

main/lib/core/src/DataCollector.cc, user/eudet/misc/conf/eudet_tlu/autotrigger/eudet_one-DC.conf, user/eudet/misc/conf/eudet_tlu/beam/eudet_one-DC.conf, user/eudet/misc/starting_scripts/02_eudet_tlu_telescope_itk-rc
For the beam telescope at high continuous rate, the Logger run into a buffer limit due to the OnlineMonitor. Thus, the fraction of data can be set by the parameter EUDAQ_DATACOL_SEND_MONITOR_FRACTION in the DataCollector.
(And: work around solution for automatic run restart from atlasitk runcontrol, as a ToDo for user/eudet or even global.)
=> user/eudet: Fraction of data send to the Monitor, set to 10

main/lib/core/src/RawEvent2StdEventConverter.cc
Right now, event converter cannot properly fail because the returned `false` boolean from the event converter is not propagated by the `RawEvent2StdEventConverter` class.
This PR fixes that.
=> Correctly propagate the result of event decoding

gui/src/euRun.cc
This PR enables the feature to log user information from the RC-GUI logging line to a default `LogCollector.log`
=> Let the RunControlGUI connect to the default LogCollector

main/lib/core/include/eudaq/CommandReceiver.hh, main/lib/core/src/CommandReceiver.cc
This PR adds a function called `Disconnect()` to the CommandReceiver, which allows a producer to disconnect from the RunControl, also freeing the connection. 
@eyiliu implemented everything required to do so. I only had to create the function.
=> added disconnect option for all producers

main/lib/core/include/eudaq/StandardEvent.hh, main/lib/core/include/eudaq/StandardPlane.hh, main/lib/core/src/StandardEvent.cc, main/lib/core/src/StandardPlane.cc, user/tlu/module/src/TluRawEvent2StdEventConverter.cc
This PR extends the `StandardPlane` and `StandardEvent` classes by the possibility of storing timestamps. This is required for AIDA devices when using the EUDAQ-internal Raw->StdEvent conversions on the offline analysis.
IMHO the `StandardPlane` class should be completely rewritten, but that's a different story.
=> AIDA: Add timestamps to StdPlane pixels & StdEvent

user/tlu/hardware/src/AidaTluController.cc
The AIDATluConteroller has the function `uint32_t AidaTluController::I2C_enable(char EnclustraExpAddr)` without a return value, which causes the AIDATLUProducer to crash on my machines - added a return 1 at the end to fix this. The return value is not used in the code and it might be a good idea to fix that properly.
=> fixed bug in I2C, that causes TLU not to scan I2C bus

main/lib/core/include/eudaq/StandardEvent.hh
We need to initialize event start and end timestamps to zero, otherwise they might contain random memory content.
=> StandardEvent: initialize event start/end with zero

python/PyEUDAQWrapper.py
To be able to use BDAQ53 with EUDAQ the Python wrapper needs Python 3 compatibility. This is added with this PR. The functionality of this wrapper with Python 3 is successfully tested within the [BDAQ53 CI pipeline](https://gitlab.cern.ch/silab/bdaq53/-/jobs/4793744).
=> Python 3 compatibility for Python EUDAQ Wrapper

main/lib/core/include/eudaq/StandardEvent.hh, user/caribou/module/src/ATLASPixEventConverter.cc, user/caribou/module/src/CLICpix2EventConverter.cc, user/eudet/module/src/NiRawEvent2StdEventConverter.cc, user/timepix3/module/src/Timepix3Event2StdEventConverter.cc, user/tlu/module/src/TluRawEvent2StdEventConverter.cc
This is a PR intended to solve the issue raised in #576 
It adds a new member plus setter/getter to StdEvent to store the detector type. It has to be set explicitly by the StdEventConverter of the respective detector.
=> Allow retrieval of detector type from StdEvent

main/lib/core/src/StandardPlane.cc, user/eudet/module/src/NiRawEvent2StdEventConverter.cc
Digging into the issue #592 I found a bug in the NiRawDataConversion and the StandardEvent. The issue is present since the merge of PR #532. Fortunately, it is not affecting the pixel addresses, only the timestamps are wrongly/randomly assigned.
It would be nice if @mwilliams294 could test if her issues are fixed.
=> Bugfix in the StdEvent

CMakeLists.txt
…and only move to final destination when installing.
Without this fix, the cmake directive `export(PACKAGE eudaq)` will mislead CMake into using the `eudaqConfig.cmake` in the build folder - and then not finding `eudaqTargets.cmake`.
=> CMake: create targets file in build folder

CMakeLists.txt
Commit 526a258420b93534898db235d5b283cbbc0bed61 resulted in only `eudaqTargets.cmake` being copied to the install location, while `eudaqTargets-<BUILD_FLAVOR>.cmake` have been left behind. They are required because they contain the `IMPORTED_LOCATION` statement used to locate the libraries at link time.
=> Fix Installation of Target Files

main/lib/core/include/eudaq/Factory.hh, main/lib/core/include/eudaq/LogMessage.hh, main/lib/core/src/LogMessage.cc
Dear Eudaq developers,
as you may know, for the CMS Phase II SW we uses Eudaq to run at the Desy test beam.
Since last time we did a testbeam there, we raised the requirements in the C++ flags and now we are having problem in compiling the Ph2_ACF with your code.
The errors are due to the flag pedantic and overloaded-virtual
The first ones are caused by some ';' at the end of functions in Factory.hh that I removed.
The overloaded-virtual error caused is caused by "virtual void LogMessage::Print(std::ostream &) const" which hides "virtual void Status::Print(std::ostream &, size_t offset = 0) const"
I am not totally sure if the solution I propose in the PR is addressing the aim of this function, but a function name change would mean a much larger intervention that I'm not confident to do.
I …
=> Solved error when using pedantic and overloaded-virtual flags

monitors/rootmonitor/CMakeLists.txt, monitors/rootmonitor/include/eudaq/ROOTMonitorWindow.hh, monitors/rootmonitor/src/ROOTMonitorWindow.cc, user/example/module/CMakeLists.txt, user/example/module/src/Ex0ROOTMonitor.cc
An example of a ROOT monitor is introduced in the `user/example` sub-package.
Additionally, the `TGraph2D`-specific procedure has been implemented in the `ROOTMonitorWindow` clearing method.
A follow-up PR will propose additions in the users' manual for the documentation of this ROOT monitor.
=> ROOT monitor example

main/lib/lcio/CMakeLists.txt
Explained as title. 
External project was not able to build against eudaq when eudaq_lcio had been enabled.
=> lib/lcio: fix cmake for compile external project against eudaq and lcio

monitors/rootmonitor/src/ROOTMonitorWindow.cc
In order to compile with ROOT v6-22-02, a missing `#include` statement was added.
=> compatibility for ROOT v6-22-02

user/tlu/module/src/TluRawEvent2StdEventConverter.cc
StdEventMonitor does not provide a `EudaqConfigSPC` object but a `nullptr` which crashes the converter unless we account for it.
@jekroege @lhuth
=> TLU converter: do not presume that we have a config object

CMakeLists.txt
When adding eudaq as a submodule to other repositories, it's currently impossible to override options from master CMakeLists.txt files.
This can be fixed by requesting to explicitly use the "new" policy CMP0077.
=> added policy to use new cmake policy to allow overriding options

gui/src/euRun.cc
@simonspa  found a bug that the configuration file is not updated if a single connection is (re)-configured. This MR fixes this. Now the config/ini is automatically updated each time before it is used
=> Always update the config beofre sending it

main/lib/python/src/PybindStatus.cc
When compiling against python 3.8, the PyStatus class in main/lib/python/src/PybindStatus.cc has a name clash with a typedef from cython, more precisely: `include/python3.8/cpython/pystate.h`
Renaming this class seems to fix it, but of course, I don't know if this breaks things down the line. Please review!
=> class name clash for python 3.8

user/eudet/misc/conf/aida_tlu/beam/all_mixed-mode_multiple-DCs.conf, user/eudet/misc/conf/aida_tlu/beam/all_mixed-mode_one-DC.conf, user/eudet/misc/conf/aida_tlu/beam/all_standard-mode_multiple-DCs.conf, user/eudet/misc/conf/aida_tlu/beam/all_standard-mode_one-DC.conf, user/eudet/misc/conf/aida_tlu/beam/only-fei4_standard-mode_multiple-DCs.conf, user/eudet/misc/conf/aida_tlu/beam/only-telescope_standard-mode_multiple-DCs.conf, user/eudet/misc/conf/aida_tlu/beam/only-telescope_standard-mode_one-DC.conf, user/eudet/misc/conf/aida_tlu/beam/only-tlu.conf, user/eudet/misc/hw_conf/aida_tlu/aida_tlu_address-fw_version_26.xml, user/eudet/misc/hw_conf/aida_tlu/aida_tlu_connection.xml
We have updated the default firmware of the AIDA-TLUs at the DESY-II test beam. This comes with a few changes in the address tables that we now load as default.
In addition, the PMT voltages options are added to all config files.
=> Updating configruation for aida-tlu firmware 0x26 & adding pmt voltages to eudet/aida_tlu configs

user/timepix3/module/src/Timepix3Producer.cxx
XML file was not read anew when reconfiguring in EUDAQ.
=> Timepix3: make sure to reconfigure the chip

user/piStage/module/src/PIStageProducer.cc
Since no return type is given nor needed, the setup function is a void now
=> fix_stage_producer

main/lib/core/src/DataCollector.cc
Found by Annika Vauth - we should *always* send the first event to the online monitor, because some detectors add vital information for decoding in the BORE tags.
It would be nicer to check for `evt->IsBORE()` but according to Annika, this flag is **never** positive in the DataCollector for some reason. :shrug:
=> DataCollector: always send first event to monitor

user/piStage/module/src/PIStageProducer.cc
Fix for bug discovered by @asimancas - `int` as default value will lead to parsing of value as int.
=> PiStageController: Fix Parsing

main/lib/python/CMakeLists.txt
The current build option generates the `dylib` file based on Apple's default configuration.
To import the `pyeudaq` library to MacOS system, I forced to generate the `so` file.
=> Update build option for MacOS

main/lib/core/include/eudaq/FileDeserializer.hh, main/lib/core/src/FileDeserializer.cc
The deserializer can sometimes cryptically fail on corrupt files.
This PR improves the error messages it emits.
=> improved error messages of deserializer

main/lib/core/src/RunControl.cc
According to documentation the FSM should allow connections in CONFIGURED state. This was disabled both when starting a run (correct) and when configuring (wrong). Removed the second occurrence.
=> FIX: FSM does not allow connection in CONFIGURED state

main/lib/core/CMakeLists.txt, main/lib/core/include/eudaq/Exception.hh, main/lib/core/src/Exception.cc, main/lib/core/src/LinkDef.h, monitors/rootmonitor/CMakeLists.txt
eudaq does not generate any dictionaries. This makes it hard to use in interactive shells or with python.
This PR sets out to at least generate dictionaries for the exception classes, so that exceptions thrown within eudaq can be processed sensibly in python scripts.
Also, the implementation of the Exception classes is cleaned up a bit.
=> Added dictionaries

main/lib/core/CMakeLists.txt
PR #656 added a direct ROOT dependency to the EUDAQ2 core library without even checking previously if ROOT is installed and has been found by the build system. Seems like we were all lucky and had ROOT installed anyway.
...unless we tried to build for an embedded 32-bit ARM system without ROOT :wink: 
I now quietly check for ROOT presence and enable dictionary generation in case we have it, and not else. This should be fine, because for using the resulting ROOT dicts you need ROOT anyway. Sorry, circular sentence.
(cc) @ffeindt @herkerta
=> Unbreak EUDAQ2: Allow Compilation without ROOT

user/caribou/module/include/CaribouEvent2StdEventConverter.hh, user/caribou/module/src/dSiPMEventConverter.cc
* Added configuration option to check valid bit and time stamp consistency. If inconsistent event is dropped. Defaults to off.
* Added configuration option to set an effective number of bits for fine time-stamp decoding. Defaults to 32, the nominal number of bits.
* Always forwarding event time stamps. Event building by trigger ID can be forced in corry.
* Removing commented code and cleaning up debugging output.
=> dsipm updates

user/caribou/README.md, user/caribou/module/src/dSiPMEventConverter.cc
When running multiple devices, this should be added to differentiate the devices.
/cc @simonspa
=> Caribou/dSiPM: add plane_id option

main/lib/core/include/eudaq/Producer.hh
Unfortunately compiling MuPix8 with EUDAQ support is only possible with this patch. Separate to #696 since this changes core components and I'm not sure what the policy here is.
=> Adjust Producer.hh to support MuPix8_DAQ

main/lib/python/CMakeLists.txt
`FindPythonLibs` is [deprecated](https://cmake.org/cmake/help/latest/module/FindPythonLibs.html) since `cmake==3.12`. Since Ubuntu 18 that was shipped with `cmake < 3.12` is EOL since April 2023, it might make sense to update to the newer `FindPython`.
Tested and works on Debian 12, cmake 3.25, python 3.10.
=> Update cmake FindPython

user/caribou/module/src/H2MEventConverter.cc
We should get the trigger information from the TLU, not from this device.
=> H2M: do not add trigger ID to the event

user/tlu/module/src/TluRawEvent2StdEventConverter.cc
We store `time_begin` and `time_end` in separate member variables in 'Events' and 'StdEvents'. Not entirely sure if this is healthy, but will create a lot of chaos to fix this. This way we keep them consistent at least. Should not change anything in Corry, as we are not actually using them, but it might prevent future trouble.
=> TluRawEvent2StdEventConverter: fix time stamp unit consistency.

.github/workflows/cmake.yml, README.md
Minimum extension of github actions:
- ubuntu-latest installing latest CERN ROOT and qt5/qt6 resulting in two jobs
- trying to build stdeventmonitor and gui
- adding badge to README.md
=> extending github actions: qt5/qt6 and ROOT for ubuntu

CMakeLists.txt
This reverts a few CMake linking policies which seem to have created issues with ROOT's Cling:
```
#pragma clang diagnostic pop
==== SOURCE END ====
Error in <TClingCallFunc::Exec(address, interpVal)>: Called with no wrapper, not implemented!
IncrementalExecutor::executeFunction: symbol '_ZN15OnlineMonWindow10autoUpdateEv' unresolved while linking symbol '__cf_46'!
You are probably missing the definition of OnlineMonWindow::autoUpdate()
Maybe you need to load the corresponding shared library?
Error in <TClingCallFunc::make_wrapper>: Failed to compile
==== SOURCE BEGIN ====
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wformat-security"
__attribute__((used)) __attribute__((annotate("__cling__ptrcheck(off)")))
extern "C" void __cf_46(void* obj, int nargs, void** args, …
```
=> Fix weird CLING issue

user/caribou/module/include/CaribouEvent2StdEventConverter.hh, user/caribou/module/src/H2MEventConverter.cc
Adding the possibility to read a ToT calibration file. 
If a ToT calibration file is not provided in the Corryvreckan configuration, the ToT measurement will be used in the analysis (as done currently). 
This method is based on the Timepix3 calibration, and many parts of the code are directly copied from here: https://github.com/eudaq/eudaq/blob/master/user/timepix3/module/src/Timepix3Event2StdEventConverter.cc
cc: @ffeindt
=> H2M: ToT calibration

user/tlu/hardware/include/AidaTluI2c.hh
As there was… an explicit include missing (bug that was not visible) it did not compile anymore. Fixed by including cstdint.
=> FIX: GCC13 does not include cstdint anymore in iostream. 

main/exe/src/euCliReader.cxx, main/lib/core/include/eudaq/Time.hh, main/lib/core/include/eudaq/TransportTCP.hh, main/lib/core/include/eudaq/TransportTCP_WIN32.hh, main/lib/core/src/ModuleManager.cc.in, monitors/onlinemon/include/SimpleStandardEvent.hh
euCliReader did not compile anymore on Windows. Not clear where windows.h gets pulled in now? Could be the boost from CMS? But should be isolated. This really should be cleaned up but it is a fix for the moment. Took the opportunity to clean up also some outdated root stuff.
=> Fix NOMINMAX for windows

user/caribou/module/src/DSO9254AEventConverter.cc
Fix error message. If we do not have digital data, we can not expect it to match.
=> DSO updates
